name: commons_config
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/Limeslice-Software-Foundation/commons-config

environment:
  sdk: ^3.4.3

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
