name: commons_config
description: >-
  The Commons Configuration software library provides a generic configuration 
  interface which enables a Dart/Flutter application to read configuration data 
  from a variety of sources.
version: 0.0.2
repository: https://github.com/Limeslice-Software-Foundation/commons-config

environment:
  sdk: ^3.4.3

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
